name: GitHub-Profile-3D-Contrib

on:
  schedule: # Run the workflow every day at 18:00 UTC (03:00 JST)
    - cron: "0 18 * * *"
  workflow_dispatch: # Allow manual trigger via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate 3D GitHub Profile Contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
      # Updated to use actions/upload-artifact@v3
      - uses: actions/upload-artifact@v3
        with:
          name: github-profile-3d-contrib
          path: ./path-to-artifacts # Update with actual artifact path
